cmake_minimum_required(VERSION 3.22.1)
project(PrismEngine LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(PRISM_ROOT ${CMAKE_CURRENT_SOURCE_DIR}/../../../../../engine/core)
file(GLOB_RECURSE PRISM_SOURCES CONFIGURE_DEPENDS ${PRISM_ROOT}/src/*.cpp)
add_library(prism_runtime SHARED prism_android.cpp ${PRISM_SOURCES})
target_include_directories(prism_runtime PRIVATE ${PRISM_ROOT}/include)
target_compile_options(prism_runtime PRIVATE -Wall -Wextra -Wno-unused-parameter -fexceptions -frtti)
target_link_libraries(prism_runtime PRIVATE GLESv3 EGL android log)
